# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luacs_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='luacs_backend.Terminal'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='default_permission_days',
            field=models.PositiveSmallIntegerField(blank=True, default=365, help_text='Default expiration time. If null/not set, permission will not expire.', null=True, verbose_name='default permission duration (in days)'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='max_unused_days',
            field=models.PositiveSmallIntegerField(blank=True, default=90, help_text='Max. days since last use for permission to still be valid. If null/not set, usage is not necessary.', null=True),
        ),
    ]
