# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luacs_backend', '0002_auto_20170521_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestatus',
            old_name='authorisation',
            new_name='authorization',
        ),
    ]
