# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luacs_backend', '0003_auto_20170522_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='luacsprofile',
            name='first_name',
            field=models.CharField(default='Julian', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luacsprofile',
            name='last_name',
            field=models.CharField(default='Hammer', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='granted_until',
            field=models.DateTimeField(blank=True, help_text='If not set, unlimited permission is granted.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([]),
        ),
    ]
