# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('luacs_backend', '0005_auto_20170614_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(help_text='TODO info here', max_length=10, verbose_name='ID type')),
                ('id_string', models.CharField(help_text='TODO info here', max_length=255, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='luacsprofile', to=settings.AUTH_USER_MODEL, verbose_name='backend user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='luacsprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='luacsprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='permission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='luacs_backend.Profile'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='luacs_backend.Profile'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='members',
            field=models.ManyToManyField(through='luacs_backend.Permission', to='luacs_backend.Profile'),
        ),
        migrations.DeleteModel(
            name='LuacsProfile',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('id_type', 'id_string')]),
        ),
    ]
