# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luacs_backend', '0006_auto_20170615_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='luacs_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
